[package]
name = "RustShell"
version = "0.1.0"
authors = ["Hyunmin Shin <shm1193@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
